### ISSUE TITLE
There were no tensor arguments to this function

### ISSUE THREAD

**Issue by nerdyrodent** [lucidrains/deep-daze#44]
Not quite sure what I'm doing wrong yet. Any ideas?

imagine "A rainbow in the forest" --deeper --save_every=200 --open_folder=False --epochs=2

> Starting up...
> Imagining "A rainbow in the forest" from the depths of my weights...
> loss: -44.91: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1050/1050 [12:29<00:00,  1.40it/s]
> loss: -46.91: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 1049/1050 [12:38<00:00,  1.38it/s]
> epochs:  50%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                  | 1/2 [25:08<25:08, 1508.57s/it]
> Traceback (most recent call last):
>   File "/home/nerdy/anaconda3/envs/big-sleep/bin/imagine", line 8, in <module>
>     sys.exit(main())
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/deep_daze/cli.py", line 91, in main
>     fire.Fire(train)
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
>     target=component.__name__)
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/deep_daze/cli.py", line 87, in train
>     imagine()
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/deep_daze/deep_daze.py", line 366, in forward
>     loss = self.train_step(epoch, i)
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/deep_daze/deep_daze.py", line 319, in train_step
>     loss = self.model(self.encoded_text)
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/nerdy/anaconda3/envs/big-sleep/lib/python3.7/site-packages/deep_daze/deep_daze.py", line 150, in forward
>     image = torch.cat(pieces)
> RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
> 
> CPU: registered at /pytorch/build/aten/src/ATen/CPUType.cpp:2127 [kernel]
> CUDA: registered at /pytorch/build/aten/src/ATen/CUDAType.cpp:2983 [kernel]
> QuantizedCPU: registered at /pytorch/build/aten/src/ATen/QuantizedCPUType.cpp:297 [kernel]
> BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
> Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
> AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
> AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
> AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
> AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
> AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
> AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
> AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
> Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:9654 [kernel]
> Autocast: registered at /pytorch/aten/src/ATen/autocast_mode.cpp:258 [kernel]
> Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
> VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]

**Comment by lucidrains** [comment]
put in a fix here! https://github.com/lucidrains/deep-daze/releases/tag/0.4.6

**Comment by nerdyrodent** [comment]
Awesome! Thanks. I can indeed now generate images :) However, I'm needing to do a "little trick" as the final image doesn't appear to be saved? The "little trick" is to make "--save_every" 1 smaller than "--iterations". For example:

`imagine "all the people" --epochs=1 --iterations=1001 --save_every=1000`

**Comment by lucidrains** [comment]
@nerdyrodent oh yes, i introduced a bug two commits ago to resolve an issue with CLIP and CUDA, fixed in the latest! https://github.com/lucidrains/deep-daze/releases/tag/0.4.8

**Comment by lucidrains** [comment]
thank you for reporting!

**Comment by nerdyrodent** [comment]
Hm. Still not getting any images with just the following:
`imagine "A clock shaped like an egg" --epochs=1 --iterations 100`

I get an initial image with either of these, but not final image:
`imagine "A clock shaped like an egg" --epochs=1 --iterations 100 --save_progress`
`imagine "A clock shaped like an egg" --epochs=1 --iterations 100 --save_progress --save_every 100`

**Comment by lucidrains** [comment]
@nerdyrodent ok, another try :pray: https://github.com/lucidrains/deep-daze/releases/tag/0.4.9

**Comment by nerdyrodent** [comment]
Thank you very much indeed! Seems to work great now :)
